# Generated by Django 3.2.7 on 2021-09-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('categorypicture', models.ImageField(blank=True, upload_to='category_pictures')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='totalcost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=30)),
                ('productdescription', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True)),
                ('instock', models.IntegerField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('currentorders', models.CharField(blank=True, max_length=100)),
                ('rank', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(blank=True, upload_to='product_pictures')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.categories')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('orderdetailid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdetailnumber', models.IntegerField(blank=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.products')),
            ],
        ),
    ]
