# Generated by Django 3.2.7 on 2021-09-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20210914_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='website',
            field=models.URLField(max_length=40),
        ),
    ]
