# Generated by Django 3.2.7 on 2021-09-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_suppliers_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
