# Generated by Django 3.2.7 on 2021-09-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_products_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
