# Generated by Django 3.2.7 on 2021-09-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20210915_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
