# Generated by Django 3.2.7 on 2021-09-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_orders_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
