# Generated by Django 3.2.7 on 2021-09-22 01:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0016_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('review_title', models.CharField(blank=True, max_length=30, null=True)),
                ('review_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('stars', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('reviewed_time', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.products')),
            ],
        ),
    ]
