# Generated by Django 3.2.7 on 2021-09-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0018_auto_20210922_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
