# Generated by Django 3.2.7 on 2021-09-27 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0021_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('liked_time', models.DateTimeField(auto_now=True)),
                ('liked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.products')),
            ],
        ),
    ]
