# Generated by Django 3.2.7 on 2021-09-13 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(choices=[('cash', 'cash'), ('card', 'card')], default='cash', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderdate', models.DateTimeField(auto_created=True)),
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(blank=True, max_length=100)),
                ('shipment_date', models.CharField(default='7 days', max_length=30)),
                ('transactionstatus', models.BooleanField(blank=True, default=False)),
                ('deliverystatus', models.BooleanField(blank=True, default=False)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('paymentdate', models.DateTimeField(blank=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paymentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.payment')),
            ],
        ),
    ]
