# Generated by Django 3.2.7 on 2021-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('notpaid', 'notpaid')], default='notpaid', max_length=10),
        ),
    ]
