# Generated by Django 3.2.7 on 2021-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=50)),
                ('contactname', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('CHN', 'chennai'), ('DEL', 'new_Delhi'), ('KOL', 'kolkata'), ('MUM', 'mumbai'), ('BGL', 'bangalore'), ('VIZ', 'visakhapatnam'), ('HYD', 'hydrabad'), ('PUN', 'punjab'), ('RAJ', 'rajasthan')], max_length=30)),
                ('state', models.CharField(choices=[('TN', 'tamilnadu'), ('AP', 'andhra_pradesh'), ('TL', 'telangana'), ('KA', 'karnataka'), ('KL', 'kerala'), ('DL', 'delhi'), ('MH', 'maharashtra'), ('PN', 'punjab'), ('RJ', 'rajasthan')], max_length=10)),
                ('postalcode', models.CharField(max_length=6)),
                ('country', models.CharField(default='INDIA', max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('website', models.URLField(max_length=20)),
            ],
        ),
    ]
