# Generated by Django 3.2.7 on 2021-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='product_pictures'),
        ),
    ]
