# Generated by Django 3.2.7 on 2021-09-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_alter_orders_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='total',
        ),
    ]
