# Generated by Django 3.2.7 on 2021-09-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0022_products_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='likes',
        ),
    ]
