# Generated by Django 3.2.7 on 2021-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
