# Generated by Django 3.2.7 on 2021-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='type',
            field=models.CharField(choices=[('ADM', 'admin'), ('SLR', 'seller'), ('USR', 'user')], default='ADM', max_length=5),
        ),
    ]
