# Generated by Django 3.2.7 on 2021-09-13 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, choices=[('CHN', 'chennai'), ('DEL', 'new_Delhi'), ('KOL', 'kolkata'), ('MUM', 'mumbai'), ('BGL', 'bangalore'), ('VIZ', 'visakhapatnam'), ('HYD', 'hydrabad'), ('PUN', 'punjab'), ('RAJ', 'rajasthan')], max_length=5)),
                ('state', models.CharField(blank=True, choices=[('TN', 'tamilnadu'), ('AP', 'andhra_pradesh'), ('TL', 'telangana'), ('KA', 'karnataka'), ('KL', 'kerala'), ('DL', 'delhi'), ('MH', 'maharashtra'), ('PN', 'punjab'), ('RJ', 'rajasthan')], max_length=5)),
                ('postalcode', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, default='INDIA', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('ADM', 'admin'), ('SLR', 'seller'), ('USR', 'user')], default='user', max_length=5)),
                ('website', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
